### PR TITLE
fix: lint always fails on windows github runners due to line endings

### PR DESCRIPTION
**Pull request by joeflateau**

### CODE REVIEW

**Review by aladdin-add — COMMENTED** [review]
thanks for the PR! what do you think add the config in [.gitattributes](https://www.git-scm.com/docs/gitattributes), so it can also work for windows users?

**Comment by joeflateau** [comment]
@aladdin-add i'm not sure what the best practices are here, but adding gitattributes should work too

**Comment by aladdin-add** [comment]
the difference is .gitattributes not just works for gh runner - I guess some devs may encounter the issue too.

**Comment by joeflateau** [comment]
right right right. I'll change this up to use gitattributes

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks! 👍

**Comment by joeflateau** [comment]
thank you!

**Pull request merged**
